[package]
name = "rustvent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustvent-macros = { version = "0.1.0", path = "../rustvent-macros", optional = false }
